# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-08 14:59
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('bill_id', models.CharField(max_length=200)),
                ('summary', models.TextField()),
                ('status', models.CharField(
                    choices=[(1, 'Needs Review'), (2, 'Updated'),
                             (3, 'Research Complete'), (4, 'Done')],
                    max_length=200)),
                ('priority', models.CharField(
                    choices=[(1, 'High'), (2, 'Medium'), (3, 'Low')],
                    max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='BillCategories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('bill',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='legislation_tracker.bills.Bill')),
            ],
        ),
        migrations.CreateModel(
            name='InterestCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MemberOfCongress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MemberOfCongressInterests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('interest',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='legislation_tracker.bills.InterestCategory')),
                ('member_of_congress',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='legislation_tracker.bills.MemberOfCongress')),
            ],
        ),
        migrations.AddField(
            model_name='billcategories',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    to='legislation_tracker.bills.InterestCategory'),
        ),
    ]
